language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Reverse proxy
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy minhvh2027/reverseproxy:v1
  # Frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend minhvh2027/udagram-frontend:v1
  # Users microservice
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user minhvh2027/udagram-api-user:v1
  # Feed microservice
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed minhvh2027/udagram-api-feed:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  minhvh2027/reverseproxy
  - docker push  minhvh2027/udagram-frontend
  - docker push  minhvh2027/udagram-api-user
  - docker push  minhvh2027/udagram-api-feed